### ISSUE TITLE
Video File Not Appearing

### ISSUE THREAD

**Issue by cadester02** [raian621/dank-downloader#1]
The video downloads however throws a permission error stating that the file cannot be accessed as it is already open. This is happening on a Windows 10 desktop with the process failing at downloading the mp4 file.

**Comment by raian621** [comment]
So the way I initially approached the audio downloads was to download a video (mp4 w/ video and audio), then write the audio of that video file to a new audio file (mp3), and then delete the original video file. This error is likely happening because the program is attempting to delete the video file before the Windows OS is done closing it or something.

The underlying library we are using is pytube, and from what I can tell it supports audio downloads in a couple of different formats:
- mp4/audio
- webm/audio
- opus

So one way we could solve this issue is by downloading one of the audio streams and converting it to a sound file like mp3 or wav using ffmpeg.
```python
# downloader/downloader.py:download_audio
streams, length = get_pytube_streams(url, file_extension="mp4", audio_only=True)

# select highest quality stream
audio_stream = streams.order_by('bitrate').desc().first()
audio_file_path = 
# download the mp4 audio stream
audio_stream.download(file_destination)
# use ffmpeg to convert the mp4 file to mp3
audio = ffmpeg.input(audio_file_path)
ffmpeg.output(audio, audio_file_path.replace('mp4', 'mp3')).run()
```
